/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.fatec.aula.view;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lozep
 */
public class comprasInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public comprasInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        produtoPanel = new javax.swing.JPanel();
        descricaoLabel1 = new javax.swing.JLabel();
        descricaoTextField1 = new javax.swing.JTextField();
        qtdeLabel = new javax.swing.JLabel();
        valorLabel = new javax.swing.JLabel();
        qtdeFormattedTextField = new javax.swing.JFormattedTextField();
        valorFormattedTextField = new javax.swing.JFormattedTextField();
        produtosScrollPane = new javax.swing.JScrollPane();
        produtosTable = new javax.swing.JTable();
        botoesPanel = new javax.swing.JPanel();
        adicionarButton = new javax.swing.JButton();
        atualizarButton = new javax.swing.JButton();
        excluirButton = new javax.swing.JButton();
        limparButton = new javax.swing.JButton();
        resultadolPanel = new javax.swing.JPanel();
        totalLabel = new javax.swing.JLabel();
        totalFormattedTextField = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(44, 62, 80));
        setClosable(true);
        setTitle("Compras");

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        produtoPanel.setBackground(new java.awt.Color(44, 62, 80));
        produtoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        descricaoLabel1.setForeground(new java.awt.Color(255, 255, 255));
        descricaoLabel1.setText("Descrição");

        descricaoTextField1.setBackground(new java.awt.Color(44, 62, 80));
        descricaoTextField1.setForeground(new java.awt.Color(255, 255, 255));
        descricaoTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        qtdeLabel.setForeground(new java.awt.Color(255, 255, 255));
        qtdeLabel.setText("Quantidade");

        valorLabel.setForeground(new java.awt.Color(255, 255, 255));
        valorLabel.setText("Valor Unitário (R$)");

        qtdeFormattedTextField.setBackground(new java.awt.Color(44, 62, 80));
        qtdeFormattedTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        qtdeFormattedTextField.setForeground(new java.awt.Color(255, 255, 255));
        qtdeFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        valorFormattedTextField.setBackground(new java.awt.Color(44, 62, 80));
        valorFormattedTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        valorFormattedTextField.setForeground(new java.awt.Color(255, 255, 255));
        valorFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout produtoPanelLayout = new javax.swing.GroupLayout(produtoPanel);
        produtoPanel.setLayout(produtoPanelLayout);
        produtoPanelLayout.setHorizontalGroup(
            produtoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produtoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(produtoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descricaoLabel1)
                    .addComponent(qtdeLabel))
                .addGap(28, 28, 28)
                .addGroup(produtoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(produtoPanelLayout.createSequentialGroup()
                        .addComponent(qtdeFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(valorLabel)
                        .addGap(18, 18, 18)
                        .addComponent(valorFormattedTextField))
                    .addComponent(descricaoTextField1))
                .addContainerGap())
        );
        produtoPanelLayout.setVerticalGroup(
            produtoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produtoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(produtoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descricaoLabel1)
                    .addComponent(descricaoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(produtoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtdeLabel)
                    .addComponent(valorLabel)
                    .addComponent(qtdeFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        produtosTable.setBackground(new java.awt.Color(44, 62, 80));
        produtosTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        produtosTable.setForeground(new java.awt.Color(255, 255, 255));
        produtosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição", "Qtde.", "V. Unit. (R$)", "V. Total (R$)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        produtosTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                produtosTableMouseClicked(evt);
            }
        });
        produtosScrollPane.setViewportView(produtosTable);

        botoesPanel.setBackground(new java.awt.Color(44, 62, 80));
        botoesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        adicionarButton.setBackground(new java.awt.Color(44, 62, 80));
        adicionarButton.setText("Adicionar");
        adicionarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarButtonActionPerformed(evt);
            }
        });

        atualizarButton.setBackground(new java.awt.Color(44, 62, 80));
        atualizarButton.setText("Atualizar");
        atualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarButtonActionPerformed(evt);
            }
        });

        excluirButton.setBackground(new java.awt.Color(44, 62, 80));
        excluirButton.setText("Excluir");
        excluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirButtonActionPerformed(evt);
            }
        });

        limparButton.setBackground(new java.awt.Color(44, 62, 80));
        limparButton.setText("Limpar");
        limparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout botoesPanelLayout = new javax.swing.GroupLayout(botoesPanel);
        botoesPanel.setLayout(botoesPanelLayout);
        botoesPanelLayout.setHorizontalGroup(
            botoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(botoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adicionarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(atualizarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(excluirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(limparButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        botoesPanelLayout.setVerticalGroup(
            botoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botoesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adicionarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(atualizarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(excluirButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(limparButton)
                .addContainerGap())
        );

        resultadolPanel.setBackground(new java.awt.Color(44, 62, 80));
        resultadolPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        totalLabel.setBackground(new java.awt.Color(44, 62, 80));
        totalLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalLabel.setText("Total a pagar (R$)");

        totalFormattedTextField.setEditable(false);
        totalFormattedTextField.setBackground(new java.awt.Color(44, 62, 80));
        totalFormattedTextField.setForeground(new java.awt.Color(255, 255, 255));
        totalFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        totalFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalFormattedTextField.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        totalFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalFormattedTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout resultadolPanelLayout = new javax.swing.GroupLayout(resultadolPanel);
        resultadolPanel.setLayout(resultadolPanelLayout);
        resultadolPanelLayout.setHorizontalGroup(
            resultadolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultadolPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        resultadolPanelLayout.setVerticalGroup(
            resultadolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultadolPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultadolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalFormattedTextField)
                    .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(produtoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(produtosScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botoesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(resultadolPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(produtoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(produtosScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botoesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultadolPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarButtonActionPerformed
      /*  try {
            OutputStream saida = new FileOutputStream("M:\\compras.txt", false);
            saida.write((descricaoTextField1.getText()).getBytes());
            saida.write("\r\n".getBytes());
            saida.write((qtdeFormattedTextField.getText()).getBytes());
            saida.write("\r\n".getBytes());
            saida.write((valorFormattedTextField.getText()).getBytes());
            saida.write("\r\n".getBytes());            
            saida.write((totalFormattedTextField.getText()).getBytes());
            saida.write("\r\n".getBytes());
            saida.flush();
            saida.close();
                
        } catch (FileNotFoundException ex) {
        Logger.getLogger(comprasInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(comprasInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        
        String descricao = descricaoTextField1.getText();
        String qtdStr = qtdeFormattedTextField.getText();
        String valorStr = valorFormattedTextField.getText();

        if (descricao.isEmpty() || qtdStr.isEmpty() || valorStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Favor preencher todos os campos!");
            return;
        }

        int quantidade = Integer.parseInt(qtdStr);
        double valorUnitario = Double.parseDouble(valorStr.replace(',', '.'));

        double total = quantidade * valorUnitario;

        DefaultTableModel tabela;
        tabela = (DefaultTableModel) produtosTable.getModel();
        Object[] linha = {
            descricao, // coluna 1
            quantidade, // coluna 2
            valorUnitario, // coluna 3
            total // coluna 4
        };
        tabela.addRow(linha);

        

        double totalAPagar = 0.0;
        for (int i = 0; i < tabela.getRowCount(); i++) {
            totalAPagar += (double) tabela.getValueAt(i, 3);
        }
        totalFormattedTextField.setText(String.valueOf(totalAPagar)); 
        descricaoTextField1.getText();
        qtdeFormattedTextField.getText();
        valorFormattedTextField.getText();
        
               try {
            OutputStream saida = new FileOutputStream("D:\\compras.txt", true);
            saida.write((descricaoTextField1.getText()).getBytes());
            saida.write("\r\n".getBytes());
            saida.write((qtdeFormattedTextField.getText()).getBytes());
            saida.write("\r\n".getBytes());
            saida.write((valorFormattedTextField.getText()).getBytes());
            saida.write("\r\n".getBytes());            
            saida.write((totalFormattedTextField.getText()).getBytes());
            saida.write("\r\n".getBytes());
            saida.flush();
            saida.close();
                
        } catch (FileNotFoundException ex) {
        Logger.getLogger(comprasInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(comprasInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } 
               
         descricaoTextField1.setText("");
        qtdeFormattedTextField.setText("");
        valorFormattedTextField.setText("");
               
    }//GEN-LAST:event_adicionarButtonActionPerformed

    private void atualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarButtonActionPerformed

        String descricao = descricaoTextField1.getText();
        String qtdStr = qtdeFormattedTextField.getText();
        String valorStr = valorFormattedTextField.getText();

        int linhaSelecionada = produtosTable.getSelectedRow();

        int quantidade = Integer.parseInt(qtdStr);
        double valorUnitario = Double.parseDouble(valorStr.replace(',', '.'));
        double total = quantidade * valorUnitario;

        DefaultTableModel tabela = (DefaultTableModel) produtosTable.getModel();
        tabela.setValueAt(descricao, linhaSelecionada, 0);
        tabela.setValueAt(quantidade, linhaSelecionada, 1);
        tabela.setValueAt(valorUnitario, linhaSelecionada, 2);
        tabela.setValueAt(total, linhaSelecionada, 3);

        descricaoTextField1.setText("");
        qtdeFormattedTextField.setText("");
        valorFormattedTextField.setText("");

        double totalAPagar = 0.0;
        for (int i = 0; i < tabela.getRowCount(); i++) {
            totalAPagar += (double) tabela.getValueAt(i, 3);
        }
        totalFormattedTextField.setText(String.valueOf(totalAPagar));
    }//GEN-LAST:event_atualizarButtonActionPerformed

    private void excluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirButtonActionPerformed

        int linhaSelecionada = produtosTable.getSelectedRow();

        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(this, "Selecione uma linha!");
            return;
        }

        DefaultTableModel tabela;
        tabela = (DefaultTableModel) produtosTable.getModel();
        tabela.removeRow(linhaSelecionada);

        double totalAPagar = 0.0;
        for (int i = 0; i < tabela.getRowCount(); i++) {
            totalAPagar += (double) tabela.getValueAt(i, 3);
        }
        totalFormattedTextField.setText(String.valueOf(totalAPagar));
    }//GEN-LAST:event_excluirButtonActionPerformed

    private void limparButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparButtonActionPerformed
        descricaoTextField1.setText("");
        qtdeFormattedTextField.setText("");
        valorFormattedTextField.setText("");

        DefaultTableModel tabela = (DefaultTableModel) produtosTable.getModel();
        while (tabela.getRowCount() > 0) {
            tabela.removeRow(0);
        }
        totalFormattedTextField.setText("0,00");
    }//GEN-LAST:event_limparButtonActionPerformed

    private void produtosTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_produtosTableMouseClicked

        int linhaSelecionada = produtosTable.getSelectedRow();
        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(this, "Selecione uma linha!");
            return;
        }

        DefaultTableModel tabela = (DefaultTableModel) produtosTable.getModel();
        // Retirar da tabela
        Object descricaoObj = tabela.getValueAt(linhaSelecionada, 0);
        Object quantidadeObj = tabela.getValueAt(linhaSelecionada, 1);
        Object valorObj = tabela.getValueAt(linhaSelecionada, 2);
        // Colocar nos campos
        descricaoTextField1.setText(String.valueOf(descricaoObj));
        qtdeFormattedTextField.setText(String.valueOf(quantidadeObj));
        valorFormattedTextField.setText(String.valueOf(valorObj));
    }//GEN-LAST:event_produtosTableMouseClicked

    private void totalFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalFormattedTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarButton;
    private javax.swing.JButton atualizarButton;
    private javax.swing.JPanel botoesPanel;
    private javax.swing.JLabel descricaoLabel1;
    private javax.swing.JTextField descricaoTextField1;
    private javax.swing.JButton excluirButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limparButton;
    private javax.swing.JPanel produtoPanel;
    private javax.swing.JScrollPane produtosScrollPane;
    private javax.swing.JTable produtosTable;
    private javax.swing.JFormattedTextField qtdeFormattedTextField;
    private javax.swing.JLabel qtdeLabel;
    private javax.swing.JPanel resultadolPanel;
    private javax.swing.JFormattedTextField totalFormattedTextField;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JFormattedTextField valorFormattedTextField;
    private javax.swing.JLabel valorLabel;
    // End of variables declaration//GEN-END:variables
}
